### ISSUE TITLE
Not able to download small file

### ISSUE THREAD

**Issue by joseph-v** [sodafoundation/multi-cloud#912] opened 2020-03-26 12:30 UTC
Deployed multi-cloud version v0.10.0 (Daito) and tried to upload and download a small file though dashboard. Download is getting timed out and failed. If I increase file size, it successfully downloads.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to create the issue
1. Create a backed in azure, 
2. Create bucket, 
3. Upload a text file with 5 letters or less content, 
4. Try to download same file. 
Download will fail. If we add few more letters above will succeed. 

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version: V.0.10.0
- OS (e.g. from /etc/os-release):Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by joseph-v** [comment] 2020-03-26 12:32
This looks like a duplite of, issue# 906

**Comment by PravinRanjan10** [comment] 2022-02-28 14:52
duplicate of #906 . closing this

**Closed by PravinRanjan10** 2022-02-28 14:52 UTC
